name: on-push

on: ["push"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  turborepo:
    name: âš¡ï¸ on-push

    runs-on:
      labels: ubuntu-latest

    steps:

      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - name: ğŸ¥¯ Install bun
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2.1.2
        with:
          bun-version: latest

      - name: â˜„ï¸ Install dependencies
        run: bun install

      - name: âš¡ Turbo cache
        uses: rharkor/caching-for-turbo@0abc2381e688c4d2832f0665a68a01c6e82f0d6c # /v2.3.11

      - name: ğŸ¦„ Format
        run: bun run flint:check

      - name: âœ… Typecheck
        run: bun run typecheck

      - name: ğŸ§ª Test
        run: bun run test

      - name: ğŸ‘·â€ Build
        run: bun run build